### ISSUE TITLE
 MoNuSAC Dataset

### ISSUE THREAD

**Issue by sunaifei** [hasibzunair/MoNuSAC-ISBI-2020#16]
I am recently worked on the project of cell classification. I hope download the data set of “MULTI-ORGAN NUCLEI SEGMENTATION AND CLASSIFICATION CHALLENGE" for MoNuSAC 2020. I will not share data after we get the data set.

**Comment by hasibzunair** [comment]
You can get the data [here](https://monusac-2020.grand-challenge.org/Data/) after registering for it.

**Comment by sunaifei** [comment]
Sorry, I can't register. It showed that the "MoNuSAC 2020 Registration Form"  is no longer accepting responses.










At 2020-10-13 00:27:42, "Hasib Zunair" <notifications@github.com> wrote:

You can get the data here after registering for it.

**Comment by hasibzunair** [comment]
I would suggest you to contact the organizers as we were told not to share the dataset during the challenge. Leave me an email once you hear from them.
